name = "shelldeck-update"
main = "src/index.ts"
compatibility_date = "2024-12-01"
workers_dev = true

routes = [
  { pattern = "shelldeck.1clic.pro/*", zone_name = "1clic.pro" }
]

[[kv_namespaces]]
binding = "SHELLDECK_KV"
id = "860e45ea2eb84055861d946e514c8497"
